### ISSUE TITLE
Restore functionality

### ISSUE THREAD

**Issue by lowerends** [freekmurze/laravel-backup#23]
This package looks very promising, thanks!

Is there a way to restore a backup of the database with an artisan command?

**Comment by freekmurze** [comment]
Hi,

currently there is no command to perform a restore. In my mind the command should be able to:
- let you choose from which filesystem a backup should be restored, which backup from that filesystem should be restored, which files should be restored, if the backup should be restored
- perform the restore itself

I can image such a command takes a lot of work. It also should be absolutely bugfree, you don't want to overwrite the wrong files in what is potentially the production environment.

Because I don't need this functionality myself, I'm not planning on adding this in the near future. But if you feel you're up to the task, feel free to submit a pull request.
